### ISSUE TITLE
Implement Dynamic View Rendering and Navigation

### ISSUE THREAD

**Issue by KenPrz** [KenPrz/HomeSphere#12]
Description:
**Issue Summary:**
Currently, the application's user interface lacks the ability to dynamically render views based on user interactions within the navigation menu. This hampers the user experience by not allowing seamless transitions between different sections of the application.

**Proposed Changes:**
To achieve dynamic view rendering, the following steps will be taken:

1. **View Sections:** Add unique IDs to different view sections within the HTML structure. For instance, sections for the Home view, Appliances view, Rooms view, etc., will be marked with their respective IDs.

2. **Navigation Links:** Update navigation links to include an `onclick` event handler. This handler will trigger a JavaScript function (`showView`) with the appropriate view ID as a parameter.

3. **JavaScript Function (`showView`):** The JavaScript function will handle the toggling of view visibility. It will hide all view sections and then display the selected view section based on the ID passed as an argument.

**Example Implementation:**
```blade
<!-- Add IDs to your view sections -->
<div id="homeView" class="...">
    <!-- Home view content -->
</div>
<div id="appliancesView" class="..." style="display: none;">
    <!-- Appliances view content -->
</div>
<!-- ... (other view sections) -->

<!-- Update your navigation links -->
<li class="p-2 hover:bg-slate-400 rounded-lg w-full transition-colors duration-500 ease-in-out">
    <a href="#" class="flex items-center p-2" onclick="showView('homeView')">
        <!-- ... -->
    </a>
</li>
<li class="p-2 hover:bg-slate-400 rounded-lg w-full transition-colors duration-500 ease-in-out">
    <a href="#" class="flex items-center p-2" onclick="showView('appliancesView')">
        <!-- ... -->
    </a>
</li>
<!-- ... (other navigation links) -->

<script>
    // JavaScript function to toggle view visibility
    function showView(viewId) {
        // Hide all views
        const views = document.querySelectorAll('.view-section');
        views.forEach(view => view.style.display = 'none');

        // Show the selected view
        const selectedView = document.getElementById(viewId);
        selectedView.style.display = 'block';
    }
</script>
```

**Tasks:**
- [ ] Implement dynamic view rendering in the HTML structure.
- [ ] Update navigation links to trigger the `showView` function.
- [ ] Develop and test the `showView` JavaScript function for toggling view visibility.
